blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.blog_index, name='blog_index'),
]

compte/urls.py
from django.urls import path, re_path
from . import views


app_name = 'compte'


urlpatterns = [
    path('', views.compte_index, name='compte_index'),
]

destination/urls.py
from django.urls import path, re_path
from . import views


app_name = 'destination'

urlpatterns = [
    path('', views.destination_index, name='destination_index'),
]

tourismegui/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('blog/', include('blog.urls')),
    path('compte/', include('compte.urls')),
    path('destination/', include('destination.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

compte/models.py
from django.db import models

# Create your models here.

destination/models.py
from django.db import models

# Create your models here.

reservation/models.py
from django.db import models

# Create your models here.

compte/forms.py
from django import forms


#Formulaires 

app_name = 'compte'

tourismegui/forms.py
from django import forms

#Our form here

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.


app_name = 'blog'


def blog_index(request):
    return HttpResponse("<h1>Voici le Blog !</h1>")

compte/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

# Create your views here.

app_name = 'compte'

def compte_index(request):
    return HttpResponse('<h1> Page utilisateur ! </h1>')

destination/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

# Create your views here.

app_name = 'destination'


def destination_index(request):
    return HttpResponse('<h1> Page des destinations ! </h1>')

reservation/views.py
from django.shortcuts import render

# Create your views here.

tourismegui/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader


def index(request):
    return render(request, 'pages/index.html')

templates/pages/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> ACCEUIL | TourismeGui </title>
    <style>
        body{
            background-color: rgb(9, 8, 8);
            color: rgb(9, 9, 226);
        }
        .nav{
            position: relative;
            text-align: center;
        }
        .nav li{
            text-decoration: none;
            display: inline;
            margin: 0 8em 0 8em;
        }
        .nav a{
            text-decoration: none;
            font-size: 25px;
        }
        .nav a:hover{
            color: chocolate;
            box-shadow: 6px 6px olivedrab;
        }
    </style>
</head>
<body>
    <div class="nav">
        <li><a href="{% url 'blog:blog_index'  %}">Blog</a></li>
        <li><a href="{% url 'destination:destination_index' %}">Destination</a></li>
        <li><a href="{% url 'compte:compte_index' %}">Compte</a></li>
    </div>
    <h1>Bienvenu sur notre site de tourisme ! </h1>
    
</body>
</html>